export const COUNTRY_CODE = [
  { display: "🇨🇴 +57", value: "57", pais: "Colombia" },
  { display: "🇦🇷 +54", value: "54", pais: "Argentina" },
  { display: "🇧🇴 +591", value: "591", pais: "Bolivia" },
  { display: "🇨🇱 +56", value: "56", pais: "Chile" },
  { display: "🇨🇷 +506", value: "506", pais: "Costa Rica" },
  { display: "🇨🇺 +53", value: "53", pais: "Cuba" },
  { display: "🇪🇨 +593", value: "593", pais: "Ecuador" },
  { display: "🇸🇻 +503", value: "503", pais: "El Salvador" },
  { display: "🇪🇸 +34", value: "34", pais: "España" },
  { display: "🇬🇹 +502", value: "502", pais: "Guatemala" },
  { display: "🇭🇳 +504", value: "504", pais: "Honduras" },
  { display: "🇲🇽 +52", value: "52", pais: "México" },
  { display: "🇳🇮 +505", value: "505", pais: "Nicaragua" },
  { display: "🇵🇦 +507", value: "507", pais: "Panamá" },
  { display: "🇵🇾 +595", value: "595", pais: "Paraguay" },
  { display: "🇵🇪 +51", value: "51", pais: "Perú" },
  { display: "🇩🇴 +1", value: "1", pais: "República Dominicana" },
  { display: "🇺🇾 +598", value: "598", pais: "Uruguay" },
  { display: "🇻🇪 +58", value: "58", pais: "Venezuela" },
];
