export const SERVICES = [
  { display: "", value: "" },
  { display: "Alimentos/Gastronomía", value: "alimentos_gastronomia" },
  { display: "Automotores", value: "automotores" },
  { display: "Estética", value: "estetica" },
  { display: "Educación", value: "educacion" },
  { display: "Comercios/Servicios", value: "comercios_servicios" },
  { display: "Construcción", value: "construccion" },
  { display: "Entidades/Instituciones", value: "entidades_instituciones" },
  { display: "Estudiantes", value: "estudiantes" },
  { display: "eCommerce", value: "ecommerce" },
  { display: "Hogar/Bazar", value: "hogar_bazar" },
  { display: "Inmobiliaria", value: "inmobiliaria" },
  { display: "Textil", value: "textil" },
  { display: "Marketing Digital", value: "marketing_digital" },
  { display: "Startup", value: "startup" },
  { display: "Salud", value: "salud" },
  { display: "Transporte/Logística", value: "transporte_logistica" },
  { display: "Turismo/Hotelería", value: "turismo_hoteleria" },
  { display: "Venta por Catálogo", value: "venta_por_catalogo" },
  { display: "Veterinaria/Petshop", value: "veterinaria_petshop" },
  { display: "Farmacéutica", value: "farmaceutica" },
  { display: "Otros", value: "otros" },
];
